// @ts-ignore
import componentsGallery from './samples/01-components-gallery.yaml'
// @ts-ignore
import formulas from './samples/02-formulas.yaml'
// @ts-ignore
import asyncFormulas from './samples/03-async-formulas.yaml'
// @ts-ignore
import validation from './samples/04-validation.yaml'
// @ts-ignore
import conditionalActions from './samples/05-conditional-actions.yaml'
// @ts-ignore
import subforms from './samples/06-subforms.yaml'
// @ts-ignore
import tabsLayout from './samples/07-tabs-layout.yaml'
// @ts-ignore
import richText from './samples/08-rich-text.yaml'
// @ts-ignore
import clinicalWorkflow from './samples/10-clinical-workflow.yaml'
// @ts-ignore
import delegatedEdition from './samples/11-delegated-edition.yaml'
import specialtyIndexJson from './samples/curated/index.json'

import { css, html, LitElement } from 'lit'

import { Form } from '../src/components/model'
import { state } from 'lit/decorators.js'
import YAML from 'yaml'
import { getStoredLanguage } from './bootstrap'

import './decorated-form'
import './theme-language-picker'

import { DecoratedForm } from './decorated-form'

type Sample = {
	slug: string
	title: string
	description: string
	form: Form
}

// Generated by tools/convert-legacy/build-specialty-index.ts from app/samples/curated/
// (a git submodule: icure/speciality-forms).
type SpecialtyFormEntry = { file: string; id: string | null; title: string; embeds: string[] }
const SPECIALTY_INDEX = specialtyIndexJson as Record<string, SpecialtyFormEntry[]>

// A handful of the specialty slugs don't read well once the language suffix is stripped
// (e.g. "plasticandreparatorysurgery" has no word boundaries); override those, fall back
// to a simple capitalization for the rest.
const SPECIALTY_LABELS: Record<string, string> = {
	'nose-throat-ear': 'Nose, Throat & Ear',
	ophtalmology: 'Ophthalmology',
	orthopedy: 'Orthopedics',
	pediatry: 'Pediatrics',
	persphysician: 'General Practice',
	plasticandreparatorysurgery: 'Plastic & Reparatory Surgery',
}

function specialtyLabel(key: string): string {
	if (key.startsWith('common_')) {
		return 'Common'
	}
	const base = key.replace(/-(fr|nl|en)$/, '')
	return SPECIALTY_LABELS[base] ?? base.charAt(0).toUpperCase() + base.slice(1)
}

// Which specialty directories are in scope for the app's current language, common_* first.
function specialtiesForLanguage(lang: string): string[] {
	const commonKey = `common_${lang}`
	const suffix = `-${lang}`
	return Object.keys(SPECIALTY_INDEX)
		.filter((key) => key === commonKey || key.endsWith(suffix))
		.sort((a, b) => {
			const aCommon = a.startsWith('common_')
			const bCommon = b.startsWith('common_')
			return aCommon !== bCommon ? (aCommon ? -1 : 1) : a.localeCompare(b)
		})
}

// A form is a subform, rather than a top-level entry, if some other form in the same
// specialty directory embeds it (as a Subform.forms value) — regardless of whether that
// referencing form is itself still standalone after de-duplicating forms shared across
// specialties into common_fr/common_nl.
function splitTopAndSubforms(entries: SpecialtyFormEntry[]): { top: SpecialtyFormEntry[]; subforms: SpecialtyFormEntry[] } {
	const embedded = new Set<string>()
	entries.forEach((e) => e.embeds.forEach((id) => embedded.add(id)))
	const top: SpecialtyFormEntry[] = []
	const subforms: SpecialtyFormEntry[] = []
	entries.forEach((e) => (e.id && embedded.has(e.id) ? subforms : top).push(e))
	return { top, subforms }
}

function fileStem(file: string): string {
	return file.replace(/\.json$/, '')
}

class DemoApp extends LitElement {
	private samples: Sample[] = [
		{
			slug: '01-components-gallery',
			title: '01 — Components gallery',
			description: 'Every field type once.',
			form: Form.parse(YAML.parse(componentsGallery)),
		},
		{
			slug: '02-formulas',
			title: '02 — Formulas',
			description: 'Sync cross-field computed properties (BMI, age, totals).',
			form: Form.parse(YAML.parse(formulas)),
		},
		{
			slug: '03-async-formulas',
			title: '03 — Async formulas',
			description: 'Computed properties that return Promises.',
			form: Form.parse(YAML.parse(asyncFormulas)),
		},
		{
			slug: '04-validation',
			title: '04 — Validation',
			description: 'Required, range, regex and cross-field validators.',
			form: Form.parse(YAML.parse(validation)),
		},
		{
			slug: '05-conditional-actions',
			title: '05 — Conditional logic & actions',
			description: 'Show/hide, readonly, action button + payload.',
			form: Form.parse(YAML.parse(conditionalActions)),
		},
		{
			slug: '06-subforms',
			title: '06 — Subforms',
			description: 'Parent form with repeatable child encounters.',
			form: Form.parse(YAML.parse(subforms)),
		},
		{
			slug: '07-tabs-layout',
			title: '07 — Tabs & layout',
			description: 'Multi-tab form on the 24-column grid.',
			form: Form.parse(YAML.parse(tabsLayout)),
		},
		{
			slug: '08-rich-text',
			title: '08 — Rich text schemas',
			description: 'One text-field per ProseMirror schema.',
			form: Form.parse(YAML.parse(richText)),
		},
		{
			slug: '10-clinical-workflow',
			title: '10 — Clinical workflow',
			description: 'End-to-end consultation form using every feature.',
			form: Form.parse(YAML.parse(clinicalWorkflow)),
		},
		{
			slug: '11-delegated-edition',
			title: '11 — Delegated edition',
			description: 'Token field that delegates clicks to a host action.',
			form: Form.parse(YAML.parse(delegatedEdition)),
		},
	]

	@state() private rendererMode: 'form:tab' | 'card' = 'form:tab'
	@state() private selectedSlug: string = this.initialSlug()
	@state() private expandedSpecialties: Set<string> = new Set()
	@state() private expandedSubforms: Set<string> = new Set()

	// Specialty forms are lazily imported on selection (there are hundreds of them, some
	// sizeable), so they're cached here rather than parsed up front like the YAML samples.
	private specialtyFormCache = new Map<string, Form>()
	private loadingSpecialtySlug?: string

	private initialSlug(): string {
		const fromHash = location.hash.replace(/^#/, '')
		if (this.samples?.find((s) => s.slug === fromHash) || this.resolveSpecialtyHash(fromHash)) {
			return fromHash
		}
		// `samples` isn't initialised yet when this runs from the field initialiser, and an
		// empty/unrecognised hash falls back to the first sample's slug.
		return '01-components-gallery'
	}

	private get currentFormElementId(): string | undefined {
		const sample = this.samples.find((s) => s.slug === this.selectedSlug)
		if (sample) {
			return sample.form.id ?? sample.form.form
		}
		const form = this.specialtyFormCache.get(this.selectedSlug)
		return form ? form.id ?? form.form : undefined
	}

	private resolveSpecialtyHash(slug: string): { specialty: string; file: string } | undefined {
		const slash = slug.indexOf('/')
		if (slash <= 0) {
			return undefined
		}
		const specialty = slug.slice(0, slash)
		const file = slug.slice(slash + 1)
		const match = SPECIALTY_INDEX[specialty]?.find((e) => fileStem(e.file) === file)
		return match ? { specialty, file } : undefined
	}

	private selectSample(slug: string) {
		this.selectedSlug = slug
		if (location.hash.replace(/^#/, '') !== slug) {
			history.replaceState(null, '', `#${slug}`)
		}
	}

	private selectSpecialtyForm(specialty: string, file: string) {
		const slug = `${specialty}/${file}`
		this.selectedSlug = slug
		if (location.hash.replace(/^#/, '') !== slug) {
			history.replaceState(null, '', `#${slug}`)
		}
		void this.loadSpecialtyForm(specialty, file)
	}

	private async loadSpecialtyForm(specialty: string, file: string): Promise<void> {
		const slug = `${specialty}/${file}`
		if (this.specialtyFormCache.has(slug)) {
			return
		}
		this.loadingSpecialtySlug = slug
		this.requestUpdate()
		try {
			const mod = (await import(`./samples/curated/${specialty}/${file}.json`)) as { default: unknown }
			this.specialtyFormCache.set(slug, Form.parse(mod.default as never))
		} finally {
			if (this.loadingSpecialtySlug === slug) {
				this.loadingSpecialtySlug = undefined
			}
			this.requestUpdate()
		}
	}

	private toggleSpecialty(specialty: string) {
		const next = new Set(this.expandedSpecialties)
		next.has(specialty) ? next.delete(specialty) : next.add(specialty)
		this.expandedSpecialties = next
	}

	private toggleSubforms(specialty: string) {
		const next = new Set(this.expandedSubforms)
		next.has(specialty) ? next.delete(specialty) : next.add(specialty)
		this.expandedSubforms = next
	}

	// Expands the tree down to whatever specialty form the hash points at, and starts
	// loading it — used both on direct hash navigation and on first mount.
	private revealSelection() {
		const resolved = this.resolveSpecialtyHash(this.selectedSlug)
		if (!resolved) {
			return
		}
		if (!this.expandedSpecialties.has(resolved.specialty)) {
			this.expandedSpecialties = new Set(this.expandedSpecialties).add(resolved.specialty)
		}
		const { subforms } = splitTopAndSubforms(SPECIALTY_INDEX[resolved.specialty] ?? [])
		if (subforms.some((e) => fileStem(e.file) === resolved.file) && !this.expandedSubforms.has(resolved.specialty)) {
			this.expandedSubforms = new Set(this.expandedSubforms).add(resolved.specialty)
		}
		void this.loadSpecialtyForm(resolved.specialty, resolved.file)
	}

	private onHashChange = () => {
		const slug = location.hash.replace(/^#/, '')
		if (slug && this.samples.find((s) => s.slug === slug)) {
			this.selectedSlug = slug
			return
		}
		if (slug && this.resolveSpecialtyHash(slug)) {
			this.selectedSlug = slug
			this.revealSelection()
		}
	}

	static get styles() {
		return css`
			:host {
				display: block;
				height: 100vh;
			}

			.container {
				box-sizing: border-box;
				display: flex;
				height: 100%;
				border: 1px solid #cad0d5;
			}

			.master {
				flex: 2;
				padding: 6px;
				border-right: 1px solid #cad0d5;
				overflow-y: auto;
			}

			.master ul {
				list-style-type: none;
				padding: 0;
				display: flex;
				flex-direction: column;
				gap: 4px;
				margin: 8px 0;
			}

			.master ul li {
				font-family: 'Roboto', Helvetica, sans-serif;
				font-size: 12px;
				padding: 8px;
				background-color: #fcfcfd;
				border: 1px solid #dde3e7;
				cursor: pointer;
				border-radius: 2px;
			}

			.master ul li.selected,
			.master ul li:hover {
				background-color: #dce7f2;
				border-color: #dce7f2;
			}

			.master ul li .title {
				font-weight: 600;
				display: block;
			}

			.master ul li .description {
				display: block;
				color: #586069;
				margin-top: 2px;
			}

			.detail {
				background-color: #ffffff;
				flex: 9;
				padding: 10px;
				overflow-y: auto;
			}

			.renderer-toggle {
				display: flex;
				gap: 4px;
				padding: 8px;
				border-bottom: 1px solid #d4dde6;
			}

			.renderer-toggle button {
				flex: 1;
				padding: 8px 10px;
				font-size: 13px;
				border: 1px solid #b9c5d2;
				background: #ffffff;
				color: #1a1a1a;
				border-radius: 4px;
				cursor: pointer;
			}

			.renderer-toggle button.active {
				background: #1d4ed8;
				color: #ffffff;
				border-color: #1d4ed8;
			}

			.renderer-toggle button:focus-visible {
				outline: 2px solid #1d4ed8;
				outline-offset: 2px;
			}

			.section-title {
				font-family: 'Roboto', Helvetica, sans-serif;
				font-size: 11px;
				font-weight: 600;
				text-transform: uppercase;
				color: #586069;
				margin: 12px 4px 4px;
			}

			.specialty-list {
				list-style-type: none;
				padding: 0;
				margin: 4px 0;
				display: flex;
				flex-direction: column;
				gap: 2px;
			}

			.specialty-header,
			.subform-folder-header {
				display: flex;
				align-items: center;
				gap: 6px;
				font-family: 'Roboto', Helvetica, sans-serif;
				font-size: 12px;
				padding: 6px 8px;
				cursor: pointer;
				border-radius: 2px;
			}

			.specialty-header {
				font-weight: 600;
				background-color: #fcfcfd;
				border: 1px solid #dde3e7;
			}

			.specialty-header:hover {
				background-color: #dce7f2;
				border-color: #dce7f2;
			}

			.subform-folder-header {
				color: #586069;
				margin-left: 12px;
			}

			.subform-folder-header:hover {
				background-color: #eef1f4;
			}

			.chevron {
				display: inline-block;
				width: 10px;
				transition: transform 0.1s ease;
			}

			.chevron.open {
				transform: rotate(90deg);
			}

			.specialty-header .count,
			.subform-folder-header .count {
				margin-left: auto;
				color: #8a97a3;
				font-size: 11px;
			}

			.form-list {
				list-style-type: none;
				padding: 0;
				margin: 2px 0 2px 12px;
				display: flex;
				flex-direction: column;
				gap: 2px;
			}

			.form-list li {
				font-family: 'Roboto', Helvetica, sans-serif;
				font-size: 12px;
				padding: 6px 8px;
				background-color: #ffffff;
				border: 1px solid #eceff1;
				cursor: pointer;
				border-radius: 2px;
			}

			.form-list li.selected,
			.form-list li:hover {
				background-color: #dce7f2;
				border-color: #dce7f2;
			}

			.form-list.subform-list {
				margin-left: 24px;
			}

			.loading {
				padding: 16px;
				color: #586069;
				font-family: 'Roboto', Helvetica, sans-serif;
				font-size: 13px;
			}
		`
	}

	connectedCallback() {
		super.connectedCallback()
		// Sync once after construction in case the hash matched a slug only known after `samples`
		// was assigned; also expands the specialty tree and starts loading if it's a deep link.
		this.onHashChange()
		window.addEventListener('hashchange', this.onHashChange)
		window.onkeydown = (event) => {
			if ((event.key === 'Z' || event.key === 'z') && event.metaKey) {
				const target = this.shadowRoot?.getElementById(this.currentFormElementId ?? '')
				if (!target) {
					return
				}
				if (event.key === 'Z') {
					event.preventDefault()
					;(target as DecoratedForm).redo()
				} else if (event.key === 'z') {
					event.preventDefault()
					;(target as DecoratedForm).undo()
				}
			}
		}
	}

	disconnectedCallback() {
		window.removeEventListener('hashchange', this.onHashChange)
		super.disconnectedCallback()
	}

	private renderFormItem(specialty: string, entry: SpecialtyFormEntry) {
		const stem = fileStem(entry.file)
		const slug = `${specialty}/${stem}`
		const classes = slug === this.selectedSlug ? 'selected' : ''
		return html`
			<li class="${classes}" @click="${() => this.selectSpecialtyForm(specialty, stem)}">
				<span class="title">${entry.title}</span>
			</li>
		`
	}

	private renderSpecialty(specialty: string) {
		const { top, subforms } = splitTopAndSubforms(SPECIALTY_INDEX[specialty] ?? [])
		const isExpanded = this.expandedSpecialties.has(specialty)
		const subformsExpanded = this.expandedSubforms.has(specialty)
		return html`
			<li class="specialty">
				<div class="specialty-header" @click="${() => this.toggleSpecialty(specialty)}">
					<span class="chevron ${isExpanded ? 'open' : ''}">▸</span>
					<span>${specialtyLabel(specialty)}</span>
					<span class="count">${top.length + subforms.length}</span>
				</div>
				${isExpanded
					? html`
							<ul class="form-list">
								${top.map((e) => this.renderFormItem(specialty, e))}
							</ul>
							${subforms.length
								? html`
										<div class="subform-folder-header" @click="${() => this.toggleSubforms(specialty)}">
											<span class="chevron ${subformsExpanded ? 'open' : ''}">▸</span>
											<span>Subforms</span>
											<span class="count">${subforms.length}</span>
										</div>
										${subformsExpanded
											? html`<ul class="form-list subform-list">
													${subforms.map((e) => this.renderFormItem(specialty, e))}
											  </ul>`
											: ''}
								  `
								: ''}
					  `
					: ''}
			</li>
		`
	}

	render() {
		const specialtyForm = this.specialtyFormCache.get(this.selectedSlug)
		const isSpecialtySelection = !!this.resolveSpecialtyHash(this.selectedSlug)
		return html`
			<div class="container">
				<div class="master">
					<theme-language-picker></theme-language-picker>
					<div class="renderer-toggle" role="group" aria-label="Renderer mode">
						<button type="button" class="${this.rendererMode === 'form:tab' ? 'active' : ''}" aria-pressed="${this.rendererMode === 'form:tab'}" @click="${() => (this.rendererMode = 'form:tab')}">
							Clinician
						</button>
						<button type="button" class="${this.rendererMode === 'card' ? 'active' : ''}" aria-pressed="${this.rendererMode === 'card'}" @click="${() => (this.rendererMode = 'card')}">Card</button>
					</div>
					<ul>
						${this.samples.map(
							(s) => html`
								<li class="${s.slug === this.selectedSlug ? 'selected' : ''}" @click="${() => this.selectSample(s.slug)}">
									<span class="title">${s.title}</span>
									<span class="description">${s.description}</span>
								</li>
							`,
						)}
					</ul>
					<div class="section-title">Specialties</div>
					<ul class="specialty-list">
						${specialtiesForLanguage(getStoredLanguage()).map((specialty) => this.renderSpecialty(specialty))}
					</ul>
				</div>
				<div class="detail">
					${this.samples.map(
						(s) => html`
							<div style="${s.slug === this.selectedSlug ? '' : 'display: none;'}">
								<decorated-form id="${s.form.id ?? s.form.form}" .form="${s.form}" renderer="${this.rendererMode}"></decorated-form>
							</div>
						`,
					)}
					${isSpecialtySelection
						? specialtyForm
							? html`<decorated-form id="${specialtyForm.id ?? specialtyForm.form}" .form="${specialtyForm}" renderer="${this.rendererMode}"></decorated-form>`
							: html`<div class="loading">Loading form…</div>`
						: ''}
				</div>
			</div>
		`
	}
}

customElements.define('demo-app', DemoApp)
